# ------------ promt ------------

format = """
 (207)\
${custom.app_prec}\
$directory\
${custom.app}\
$jobs\
$fill\
$cmd_duration\
$git_status\
$git_state\
${custom.git_branch_m}\
${custom.git_branch}\
$git_branch\
$git_metrics\
${custom.github_corner}\
${custom.rb}\
${custom.js}\
${custom.ts}\
${custom.jsx}\
${custom.tsx}\
${custom.sh}\
${custom.lua}\
$time\
$line_break\
$character\
"""
right_format = """
${custom.github}\
${custom.extension_icon_space}\
"""

continuation_prompt = '▶▶ '
# ------------ move ------------
# [┌─](238)\
# [└─](238)
# $os\
# $hostname\
# ${custom.username}[:](234)${custom.hostname}\
# ------------ methods ------------

[os]
style = "white"
disabled = false
format = " [$symbol]($style)"

[custom.username]
command = "echo ${USER:0:1}"
when = "true"
format = "[$output](238)"
style = "bright-yellow"

[custom.hostname]
command = "echo ${HOST:0:1}"
when = "true"
format = "[$output](238)"
style = "bright-yellow"

[username]
show_always = true
style_user = "#3954b8 bold"
style_root = "bg:#9A348E"
format = '[$user]($style)'
disabled = false

[hostname]
ssh_symbol = " "
ssh_only = false
# format = "[$symbol$hostname](bold yellow)"
format = "[$symbol](bold green)"
disabled = false

[directory]
# style = "purple"
# style = "075" # bleu
# style = "141" # dracula
style = "039" # bleu
truncation_symbol = "\uf07c  "
home_symbol = "\uf015 "
read_only_style = "197"
read_only = "  "
truncation_length = 1
truncate_to_repo = false
format = " [$path]($style)[$read_only]($read_only_style) "

[directory.substitutions]
"Documents" = "󰈙 "
"Téléchargements" = " "
"Musique" = " "
"Images" = " "

# ------------ fill ------------
[fill]
# symbol = "─"
symbol = " "
style = "236"
# ------------ fill ------------

[character]
success_symbol = "[ ❯](207)"
# success_symbol = "[](207)"
error_symbol = "[ ](red)"
vicmd_symbol = "[ ❮](green)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[git_metrics]
disabled = true

[fossil_branch]
symbol = " "

[git_branch]
symbol = "  "
# format = "[$symbol$branch]($style)"
format = "[$branch]($style)"
style = "060"

[custom.git_branch_m]
command = "git branch --show-current"
when =  "git branch --show-current && [[ $(git branch --show-current) != *'master'* && $(git branch --show-current) != *'main'* ]]"
symbol = "  "
format = "[$symbol]($style)"
style = "048"

[custom.git_branch]
when =  "[[ $(git branch --show-current) == *'master'* || $(git branch --show-current) == *'main'* ]]"
symbol = "  "
format = "[$symbol]($style)"
style = "060"

[custom.github]
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
command = "git remote | tr '\n' ' '"
style = "237 italic"
format = "[$output ┘        ]($style)"

# [custom.github]
# when = "[[ $(git branch -a) == *'remotes/origin'* ]]"
# command = "git remote -v | head -c 6"
# style = "237 italic"
# format = "[$output ┘        ]($style)"

[custom.github_corner]
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
style = "238"
format = "[ ┐]($style)"

# [custom.github_corner]
# when = "[[ $(git branch -a) == *'remotes/origin'* ]]"
# style = "238"
# format = "[ ┐]($style)"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "white"
conflicted = " 🏳"
up_to_date = " [󰃁${count}](238)"
untracked = ' [ ${count}](035)'
ahead = " ⇡${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
behind = " ⇣${count}"
stashed = ' [ ${count}](blue)'
modified = ' [ ${count}](178)'
staged = ' [+${count}](041)'
renamed = ' [󰑕 ${count}](blue)'
deleted = ' [ ${count}](196)'

[jobs]
symbol = " "
style = "bold red"
number_threshold = 1
format = " [$symbol]($style)"

[cmd_duration]
format = "[  󰔟 $duration]($style)"
style = "220"

[memory_usage]
symbol = " "

[time]
disabled = false
time_format = "%R"
style = "189 italic"
format = " [ $time]($style) "

# ------------ custom ------------
[custom.app_prec]
symbol = ""
style = "189"
when = "[[ ${PWD} = *'app'* || ${PWD} = *'src'* ]]"
format = "[$symbol]($style) "

[custom.app]
detect_folders = ['app', 'src']
symbol = " "
format = "[$symbol ]($style)"
style = "060"

[custom.extension_icon_space]
detect_extensions = ['js', 'jsx', 'ts', 'tsx', 'rb', 'ru', 'sh', 'lua']
symbol = "  "
format = " [$symbol]($style)"
style = "bright-yellow"

[custom.js]
detect_extensions = ['js', '!ts']
symbol = " "
format = " [$symbol]($style)"
style = "yellow"

[custom.rb]
detect_extensions = ['rb', 'ru']
symbol = " "
format = " [$symbol]($style)"
style = "198"

[custom.jsx]
detect_extensions = ['jsx']
symbol = " "
format = " [$symbol]($style)"
style = "yellow"

[custom.tsx]
detect_extensions = ['tsx']
symbol = " "
format = " [$symbol]($style)"
style = "051"

[custom.ts]
detect_extensions = ['ts']
symbol = " "
format = " [$symbol]($style)"
style = "032"

[custom.css]
detect_extensions = ['css', 'scss']
symbol = " "
format = " [$symbol]($style)"
style = "128"

[custom.sh]
detect_extensions = ['sh']
symbol = " "
format = " [$symbol]($style)"
style = "035"

[custom.lua]
detect_extensions = ['lua']
symbol = " "
format = " [$symbol]($style)"
style = "063"

# [custom.stunnel]
# when = "ps aux | grep stunnel | grep -v grep"
# command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
# style = "red"
# format = "[TUNNEL OPEN for $output]($style)"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

# [directory]
# read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

# [fossil_branch]
# symbol = " "

# [git_branch]
# symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

# [hostname]
# ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

# [memory_usage]
# symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = "🪺 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "
